<?php

namespace ContainerRfHNRbz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HjSvJycService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hjSvJyc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hjSvJyc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'page' => ['privates', '.errored..service_locator.hjSvJyc.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.hjSvJyc": it references class "App\\Entity\\Page" but no such service exists.'],
            'pageRepository' => ['privates', 'App\\Repository\\PageRepository', 'getPageRepositoryService', true],
        ], [
            'page' => 'App\\Entity\\Page',
            'pageRepository' => 'App\\Repository\\PageRepository',
        ]);
    }
}
