<?php

namespace ContainerWnNRSnC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChoiceService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0K7nhAZ.App\Entity\Choice' shared service.
     *
     * @return \App\Entity\Choice
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0K7nhAZ": it references class "App\\Entity\\Choice" but no such service exists.');
    }
}
