<?php

namespace ContainerWnNRSnC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChoiceRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ChoiceRepository' shared autowired service.
     *
     * @return \App\Repository\ChoiceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ChoiceRepository'] = new \App\Repository\ChoiceRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
