<?php

namespace ContainerWnNRSnC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoryController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\StoryController' shared autowired service.
     *
     * @return \App\Controller\StoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\StoryController'] = $instance = new \App\Controller\StoryController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\StoryController', $container));

        return $instance;
    }
}
