<?php

namespace ContainerWnNRSnC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StoryRepository' shared autowired service.
     *
     * @return \App\Repository\StoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\StoryRepository'] = new \App\Repository\StoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
