<?php

namespace Container9PfEilI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RID7Fo0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rID7Fo0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rID7Fo0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'storyRepository' => ['privates', 'App\\Repository\\StoryRepository', 'getStoryRepositoryService', true],
        ], [
            'storyRepository' => 'App\\Repository\\StoryRepository',
        ]);
    }
}
