<?php

namespace Container9PfEilI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BA2TDYiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bA2TDYi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bA2TDYi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'story' => ['privates', '.errored..service_locator.bA2TDYi.App\\Entity\\Story', NULL, 'Cannot autowire service ".service_locator.bA2TDYi": it references class "App\\Entity\\Story" but no such service exists.'],
        ], [
            'story' => 'App\\Entity\\Story',
        ]);
    }
}
