<?php

namespace Container9PfEilI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L_EAHh7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L.eAHh7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L.eAHh7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'choiceRepository' => ['privates', 'App\\Repository\\ChoiceRepository', 'getChoiceRepositoryService', true],
        ], [
            'choiceRepository' => 'App\\Repository\\ChoiceRepository',
        ]);
    }
}
