<?php

namespace Container9PfEilI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gOmBg61.App\Entity\Story' shared service.
     *
     * @return \App\Entity\Story
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gOmBg61": it references class "App\\Entity\\Story" but no such service exists.');
    }
}
