<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnNRSnC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnNRSnC/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWnNRSnC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWnNRSnC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWnNRSnC\App_KernelProdContainer([
    'container.build_hash' => 'WnNRSnC',
    'container.build_id' => '60476f53',
    'container.build_time' => 1668613816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnNRSnC');
