<?php

namespace ContainerUIxAaxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U_CqreVService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.u.cqreV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u.cqreV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'story' => ['privates', '.errored..service_locator.u.cqreV.App\\Entity\\Story', NULL, 'Cannot autowire service ".service_locator.u.cqreV": it references class "App\\Entity\\Story" but no such service exists.'],
            'storyRepository' => ['privates', 'App\\Repository\\StoryRepository', 'getStoryRepositoryService', true],
        ], [
            'story' => 'App\\Entity\\Story',
            'storyRepository' => 'App\\Repository\\StoryRepository',
        ]);
    }
}
