<?php

namespace ContainerUIxAaxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCustomAuthentificatorAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AppCustomAuthentificatorAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppCustomAuthentificatorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppCustomAuthentificatorAuthenticator'] = new \App\Security\AppCustomAuthentificatorAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
