<?php

namespace ContainerUIxAaxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoryService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.bA2TDYi.App\Entity\Story' shared service.
     *
     * @return \App\Entity\Story
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bA2TDYi": it references class "App\\Entity\\Story" but no such service exists.');
    }
}
