<?php

namespace ContainerUIxAaxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTheChoiceTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TheChoiceType' shared autowired service.
     *
     * @return \App\Form\TheChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TheChoiceType'] = new \App\Form\TheChoiceType(($container->privates['App\\Repository\\PageRepository'] ?? $container->load('getPageRepositoryService')), ($container->privates['App\\Repository\\ChoiceRepository'] ?? $container->load('getChoiceRepositoryService')));
    }
}
