<?php

namespace ContainerUIxAaxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserStoryRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UserStoryRepository' shared autowired service.
     *
     * @return \App\Repository\UserStoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UserStoryRepository'] = new \App\Repository\UserStoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
