<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfHNRbz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfHNRbz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRfHNRbz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRfHNRbz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRfHNRbz\App_KernelDevDebugContainer([
    'container.build_hash' => 'RfHNRbz',
    'container.build_id' => '0757f5d1',
    'container.build_time' => 1665738963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfHNRbz');
